const Config = {
  SHOPIFY_STORE_DOMAIN: process.env.NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN || '',
  SHOPIFY_API_VERSION: process.env.NEXT_PUBLIC_SHOPIFY_API_VERSION || '',
  SHOPIFY_PUBLIC_ACCESS_TOKEN:
    process.env.NEXT_PUBLIC_SHOPIFY_PUBLIC_ACCESS_TOKEN || '',
  SHOPIFY_CLIENT_ID: process.env.NEXT_PUBLIC_SHOPIFY_CLIENT_ID || '',
  SHOPIFY_AUTH_BASE_URL: process.env.NEXT_PUBLIC_SHOPIFY_AUTH_BASE_URL || '',
  BASE_URL: process.env.NEXT_PUBLIC_BASE_URL || '',
  DOMAIN: process.env.NEXT_PUBLIC_DOMAIN || '',
  DB_URL: process.env.DB_URL || '',
}

export default Config
